ALTER TABLE "at_voice_terminations" ADD COLUMN "max_call_duration_min" integer;--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD COLUMN "target_acd_min" integer;--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD COLUMN "target_asr_percent" integer;--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD COLUMN "max_a_number_concurrent_calls" integer;--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD COLUMN "max_b_number_concurrent_calls" integer;--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD COLUMN "max_a_to_b_number_concurrent_calls" integer;--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD CONSTRAINT "at_voice_terminations_max_call_duration_min_positive" CHECK ("at_voice_terminations"."max_call_duration_min" IS NULL OR "at_voice_terminations"."max_call_duration_min" > 0);--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD CONSTRAINT "at_voice_terminations_target_acd_min_positive" CHECK ("at_voice_terminations"."target_acd_min" IS NULL OR "at_voice_terminations"."target_acd_min" > 0);--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD CONSTRAINT "at_voice_terminations_target_asr_percent_range" CHECK ("at_voice_terminations"."target_asr_percent" IS NULL OR ("at_voice_terminations"."target_asr_percent" >= 0 AND "at_voice_terminations"."target_asr_percent" <= 100));--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD CONSTRAINT "at_voice_terminations_max_a_number_concurrent_calls_positive" CHECK ("at_voice_terminations"."max_a_number_concurrent_calls" IS NULL OR "at_voice_terminations"."max_a_number_concurrent_calls" > 0);--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD CONSTRAINT "at_voice_terminations_max_b_number_concurrent_calls_positive" CHECK ("at_voice_terminations"."max_b_number_concurrent_calls" IS NULL OR "at_voice_terminations"."max_b_number_concurrent_calls" > 0);--> statement-breakpoint
ALTER TABLE "at_voice_terminations" ADD CONSTRAINT "at_voice_terminations_max_a_to_b_number_concurrent_calls_positive" CHECK ("at_voice_terminations"."max_a_to_b_number_concurrent_calls" IS NULL OR "at_voice_terminations"."max_a_to_b_number_concurrent_calls" > 0);